name: listar_flutter_pro
description: wem2017.github.io
version: 1.0.6+35
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_analytics: ^6.3.0
  firebase_messaging: ^7.0.3
  shared_preferences: ^0.5.12+4
  bloc: ^6.1.0
  url_launcher: ^5.7.10
  flutter_bloc: ^6.1.1
  device_info: ^1.0.0
  share: ^0.6.5+4
  dio: ^3.0.10
  cached_network_image: ^2.3.3
  flutter_swiper: ^1.1.6
  shimmer: ^1.1.2
  flutter_slidable: ^0.5.7
  image_picker: ^0.6.7+14
  google_maps_flutter: 1.2.0
  google_api_headers: ^0.1.1+1
  photo_view: ^0.10.3
  intro_views_flutter: ^2.8.2
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.10.0
  animated_text_kit: ^3.1.0
  firebase_core: ^0.5.3
  select_dialog: ^1.2.3
  provider: ^4.3.2+4
  multi_select_flutter: 3.1.8
  multiselect_formfield: ^0.1.5
  multi_image_picker: 4.7.15
  pretty_dio_logger: ^1.1.1
  path_provider: ^1.6.27
  modal_progress_hud: ^0.1.3
  awesome_dialog: ^1.3.2
  flutter_places: ^1.0.0+4
  geolocator: 6.2.1
  flutter_svg: 0.18.1
  app_settings: 4.0.3
  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  rename: ^1.2.0

flutter:

  assets:
    - assets/images/
    - assets/locale/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-BlackItalic.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-BoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-LightItalic.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-MediumItalic.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-ThinItalic.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Black.ttf
        - asset: assets/fonts/Merriweather-BlackItalic.ttf
        - asset: assets/fonts/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
        - asset: assets/fonts/Merriweather-Light.ttf
        - asset: assets/fonts/Merriweather-LightItalic.ttf
        - asset: assets/fonts/Merriweather-Regular.ttf
  uses-material-design: true

